language: groovy
script: ./grailsw refresh-dependencies
     && ./grailsw prod-war
before_install: openssl aes-256-cbc -K $encrypted_5fff3d721dd7_key -iv $encrypted_5fff3d721dd7_iv -in github_deploy_key.enc -out github_deploy_key -d
