language: groovy
script: ./grailsw prod war
before_install: openssl aes-256-cbc -K $encrypted_5fff3d721dd7_key -iv $encrypted_5fff3d721dd7_iv -in github_deploy_key.enc -out github_deploy_key -d
after_success: 
- $(npm bin)/set-up-ssh --key "$encrypted_XXXXXXXXXXXX_key" \
                             --iv "$encrypted_XXXXXXXXXXXX_iv" \
                             --path-encrypted-key ".travis/github_deploy_key.enc"
- scp -o "StrictHostKeyChecking no" ./target/Bookstore.0-1.war ec2-user@35.160.163.175:~/usr/share/tomcat8/webapps/ROOT.war
